# Use gmake!
TIC_REGISTRY:=
TARGET := connComp
CASTLE := /usr/imports/sc/SCsp2

# MPL := CMAM | CMMD | SP1 | SP2
MPL := SP2

# MACHINE := CM5 | SP1 | SP2
MACHINE := SP2

CFLAGS := -O4 -D${MACHINE}
LIBS   := -L/fs/nene/dbader/SCsp2/lib

include ${CASTLE}/include/split-c/Make.split-c


